// <auto-generated />
using System;
using EfData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240422192003_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Models.Entities.AuthAppUser.AppUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "869f332e-a84d-4803-af9b-91b4c679ecb9",
                            RoleId = "ab4cd34b-8232-4244-b459-cb150202c040"
                        },
                        new
                        {
                            UserId = "0d52f835-94e1-409e-b180-4f370f40f98d",
                            RoleId = "86e60536-b2ab-4ac5-85b8-e2afd8fe7058"
                        },
                        new
                        {
                            UserId = "9bc4b3f3-e392-41da-aa6a-8c65f8556192",
                            RoleId = "1b7d2e86-b210-4846-9530-16962a69af6d"
                        },
                        new
                        {
                            UserId = "2f81f8ad-5bcc-447a-bc33-7b30b87cefd7",
                            RoleId = "4899d69d-bfef-4a1b-972b-c66cc56b7a89"
                        },
                        new
                        {
                            UserId = "22472f44-f29e-4317-ac81-966e5c4a6035",
                            RoleId = "c8c2a86c-7c38-45e5-95ac-b067a19aea4f"
                        },
                        new
                        {
                            UserId = "5eb32700-9d1f-48fb-9116-cf9647747ff7",
                            RoleId = "017ba3c7-6860-48fe-a066-fe005ae54521"
                        });
                });

            modelBuilder.Entity("Models.Entities.AuthAppUser.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .IsFixedLength(false);

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(90)
                        .IsUnicode(false)
                        .HasColumnType("varchar(90)")
                        .IsFixedLength(false);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .IsFixedLength(false);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .IsFixedLength(false);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("UserinfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "869f332e-a84d-4803-af9b-91b4c679ecb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f8f6cbfe-0c85-4878-9377-a460c322243f",
                            Email = "Admin123@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN123",
                            PasswordHash = "AQAAAAIAAYagAAAAED8jUBNDZ+61XzxwTiVM4VpsAtVnnWhNjKPdaDtYv8rb8PQyO6+B1NFcMNvUJRH4nA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "69331ef8-548b-4b1b-9b84-111af0fd5c6b",
                            TwoFactorEnabled = false,
                            UserName = "Admin123"
                        },
                        new
                        {
                            Id = "0d52f835-94e1-409e-b180-4f370f40f98d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b13e807e-de68-413b-94e9-b64eb6e0247a",
                            Email = "aprueba1@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "APRUEBA1@EXAMPLE.COM",
                            NormalizedUserName = "APRUEBA1",
                            PasswordHash = "AQAAAAIAAYagAAAAEFtoNvG5WVT9BctF8zxvQ9BYrHgb+BCCIYsTFm0m+jkvgOakbRjEi1vg3hDqiXQYCA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "afd077a6-40e6-490b-bfcd-8e4ae92d5c20",
                            TwoFactorEnabled = false,
                            UserName = "Aprueba1"
                        },
                        new
                        {
                            Id = "9bc4b3f3-e392-41da-aa6a-8c65f8556192",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "71bf9be6-602d-4c96-8bd9-6e170d0f946d",
                            Email = "aprueba3@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "APRUEBA3@EXAMPLE.COM",
                            NormalizedUserName = "APRUEBA3",
                            PasswordHash = "AQAAAAIAAYagAAAAEJWGrNyAi1Yr5s5acGA4U+KmhvPucKOiGfiDRXWDLXNTQrFK61yfp6SbvxOI+lMwUg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "66a9ba42-c4f3-4c41-9b86-5f3394235296",
                            TwoFactorEnabled = false,
                            UserName = "Aprueba3"
                        },
                        new
                        {
                            Id = "2f81f8ad-5bcc-447a-bc33-7b30b87cefd7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6dcfc20f-9fc9-4e1a-a0f6-ef112c083388",
                            Email = "planeador1@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PLANEADOR1@EXAMPLE.COM",
                            NormalizedUserName = "PLANEADOR1",
                            PasswordHash = "AQAAAAIAAYagAAAAELEAzqAh3RZHLumfUgyu9aI21KLeguEsqGiqcoQCX4/Se7u72jJnRj3c9MTpC+PtfA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bfaa9915-6552-4a67-bbf6-3640153aa962",
                            TwoFactorEnabled = false,
                            UserName = "Planeador1"
                        },
                        new
                        {
                            Id = "22472f44-f29e-4317-ac81-966e5c4a6035",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9caa67fc-5ee2-4f5c-bb46-a3bf7d17419f",
                            Email = "thumano1@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "THUMANO1@EXAMPLE.COM",
                            NormalizedUserName = "THUMANO1",
                            PasswordHash = "AQAAAAIAAYagAAAAEIW30lUrF+uhjaaYmmJAQ947YKrTYfjB90GOaUpjdYOtoRP2qEDeTxM5PUI7tNz0+A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0a4c4273-91a9-429d-ba6d-8b7544d7b3df",
                            TwoFactorEnabled = false,
                            UserName = "THumano1"
                        },
                        new
                        {
                            Id = "5eb32700-9d1f-48fb-9116-cf9647747ff7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bd2daa07-a0d8-48f4-b8c6-5c72b75289a1",
                            Email = "reporte1@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "REPORTE1@EXAMPLE.COM",
                            NormalizedUserName = "REPORTE1",
                            PasswordHash = "AQAAAAIAAYagAAAAEMyDXCIpAb6UIQxu/vWgsr+oUR2OSHuAjPlMXwcJzDHDMl8Ol7RjLp13Obny6L6Xtg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "631fcfe9-478c-4f36-89bb-6f6d47ef6160",
                            TwoFactorEnabled = false,
                            UserName = "Reporte1"
                        });
                });

            modelBuilder.Entity("Models.Entities.AuthAppUser.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ab4cd34b-8232-4244-b459-cb150202c040",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "4899d69d-bfef-4a1b-972b-c66cc56b7a89",
                            Name = "planificador",
                            NormalizedName = "PLANIFICADOR"
                        },
                        new
                        {
                            Id = "86e60536-b2ab-4ac5-85b8-e2afd8fe7058",
                            Name = "supervisorPermisos",
                            NormalizedName = "SUPERVISORPERMISOS"
                        },
                        new
                        {
                            Id = "1b7d2e86-b210-4846-9530-16962a69af6d",
                            Name = "supervisorMR",
                            NormalizedName = "SUPERVISORMR"
                        },
                        new
                        {
                            Id = "c8c2a86c-7c38-45e5-95ac-b067a19aea4f",
                            Name = "th",
                            NormalizedName = "TH"
                        },
                        new
                        {
                            Id = "bf52d74f-adb0-4a8a-b8fa-bb0141ab9a29",
                            Name = "user",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "017ba3c7-6860-48fe-a066-fe005ae54521",
                            Name = "visorReportes",
                            NormalizedName = "VISORREPORTES"
                        });
                });

            modelBuilder.Entity("Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdPadre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeptName = "Empresa",
                            IdPadre = 0
                        },
                        new
                        {
                            Id = 2,
                            DeptName = "Financiero",
                            IdPadre = 1
                        },
                        new
                        {
                            Id = 3,
                            DeptName = "Ventas",
                            IdPadre = 1
                        },
                        new
                        {
                            Id = 4,
                            DeptName = "Talento Humano",
                            IdPadre = 1
                        },
                        new
                        {
                            Id = 5,
                            DeptName = "Marketing",
                            IdPadre = 3
                        });
                });

            modelBuilder.Entity("Models.Entities.Userinfo", b =>
                {
                    b.Property<int>("UserinfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserinfoId"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Badgenumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("HiredDay")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SSN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UserinfoId");

                    b.HasIndex("AppUserId")
                        .IsUnique()
                        .HasFilter("[AppUserId] IS NOT NULL");

                    b.HasIndex("Badgenumber")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Name");

                    b.HasIndex("SSN")
                        .IsUnique()
                        .HasFilter("[SSN] IS NOT NULL");

                    b.ToTable("Usersinfo");

                    b.HasData(
                        new
                        {
                            UserinfoId = 1,
                            Badgenumber = "1",
                            DepartmentId = 1,
                            Email = "gacero@example.com",
                            Name = "ACERO GLORIA"
                        },
                        new
                        {
                            UserinfoId = 2,
                            Badgenumber = "2",
                            DepartmentId = 1,
                            Email = "rbarcia@example.com",
                            Name = "BARCIA RUTH"
                        },
                        new
                        {
                            UserinfoId = 3,
                            Badgenumber = "3",
                            DepartmentId = 1,
                            Email = "elopez@example.com",
                            Name = "LOPEZ EDDY"
                        },
                        new
                        {
                            UserinfoId = 4,
                            Badgenumber = "4",
                            DepartmentId = 1,
                            Email = "dzapata@example.com",
                            Name = "ZAPATA DANIEL"
                        },
                        new
                        {
                            UserinfoId = 5,
                            Badgenumber = "55",
                            DepartmentId = 2,
                            Email = "jvillacis@example.com",
                            Name = "JOSE VILLACIS"
                        },
                        new
                        {
                            UserinfoId = 6,
                            Badgenumber = "66",
                            DepartmentId = 4,
                            Email = "pgaona@example.com",
                            Name = "PAULINA GAONA"
                        },
                        new
                        {
                            UserinfoId = 7,
                            Badgenumber = "77",
                            DepartmentId = 5,
                            Email = "jlfornell@example.com",
                            Name = "JL FORNELL"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Models.Entities.AuthAppUser.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Models.Entities.AuthAppUser.ApplicationUser", null)
                        .WithMany("AppUserClaims")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Models.Entities.AuthAppUser.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Models.Entities.AuthAppUser.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Models.Entities.AuthAppUser.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Entities.AuthAppUser.AppUserRole", b =>
                {
                    b.HasOne("Models.Entities.AuthAppUser.Role", "Role")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.AuthAppUser.ApplicationUser", "AppUser")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Models.Entities.Userinfo", b =>
                {
                    b.HasOne("Models.Entities.AuthAppUser.ApplicationUser", "AppUser")
                        .WithOne("Userinfo")
                        .HasForeignKey("Models.Entities.Userinfo", "AppUserId");

                    b.HasOne("Models.Entities.Department", "Department")
                        .WithMany("Userinfos")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Models.Entities.AuthAppUser.ApplicationUser", b =>
                {
                    b.Navigation("AppUserClaims");

                    b.Navigation("AppUserRoles");

                    b.Navigation("Userinfo");
                });

            modelBuilder.Entity("Models.Entities.AuthAppUser.Role", b =>
                {
                    b.Navigation("AppUserRoles");
                });

            modelBuilder.Entity("Models.Entities.Department", b =>
                {
                    b.Navigation("Userinfos");
                });
#pragma warning restore 612, 618
        }
    }
}
